# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Apollo Engine
subtitle: Using Engine
versions:
  - '1'
sidebar_categories:
  null:
    - index
    - apollo-tracing
  Setup:
    - setup-node
    - setup-standalone
    - setup-lambda
    - setup-virtual
  Features:
    - performance
    - schema-analytics
    - error-tracking
    - caching
    - auto-persisted-queries
    - query-batching
  Guides:
    - troubleshooting
    - 1.0-migration
    - upgrade-optics
    - billing
  Reference:
    - proto-doc
    - proxy-release-notes
github_repo: apollographql/engine-docs

apis:
  segment: awKBAQ3eIgXIChDoy119j6ab4R4tqcXr

nav_links:
  'Engine':
    url: http://engine.apollographql.com

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.apollographql.com/docs/engine/
root: /docs/engine/

# Directory
source_dir: source
public_dir: public/docs/engine
